// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('$lib/intl').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {

  },
  "ru-RU": {

  }
};
