// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<string, import("./types").Dictionary>} */
export const dictionaries = {
  "en-US": null,
  "ru-RU": null
};

/** @type {string[]} */
export const locales = ["en-US","ru-RU"];
