// Auto-generated by i18n CLI - do not edit manually
// Generated at: 2025-08-18T19:11:19.873Z

export const dictionaries = {
  "en": {
    "hello": "Hello",
    "bye": "Bye",
    "example": {
      "hello": "Hello"
    }
  }
};

export const languages = ["en"];
