// Auto-generated by i18n CLI - do not edit manually
// Generated at: 2025-09-25T14:11:19.566Z

export const dictionaries = {
  "en-US": {
    "native": "English",
    "hello": "Hello",
    "bye": "Bye",
    "example": {
      "hello": "Hello"
    },
    "items": {
      "count": {
        "0": {
          "one": "item",
          "other": "items"
        }
      }
    },
    "product": {
      "count": {
        "0": {
          "one": "product",
          "other": "products"
        }
      }
    },
    "test": {
      "cars": {
        "0": {
          "one": "car",
          "other": "cars"
        }
      }
    },
    "buttons": {
      "catalog": "Browse catalog"
    }
  },
  "en": {
    "hello": "Hello",
    "bye": "Bye",
    "example": {
      "hello": "Hello"
    },
    "items": {
      "count": (count) => {
      const forms = {"one":"item","other":"items"};
      const lang = "en"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(lang);
      const rule = pluralRules.select(count);
      
      // Direct object property access - no CLDR ordering needed!
      if (forms[rule]) {
        return forms[rule];
      }
      
      // Fallback priority: other > one > first available
      return forms.other || forms.one || Object.values(forms)[0] || '';
    }
    },
    "product": {
      "count": (count) => {
      const forms = {"one":"product","other":"products"};
      const lang = "en"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(lang);
      const rule = pluralRules.select(count);
      
      // Direct object property access - no CLDR ordering needed!
      if (forms[rule]) {
        return forms[rule];
      }
      
      // Fallback priority: other > one > first available
      return forms.other || forms.one || Object.values(forms)[0] || '';
    }
    },
    "test": {
      "cars": (count) => {
      const forms = {"one":"car","other":"cars"};
      const lang = "en"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(lang);
      const rule = pluralRules.select(count);
      
      // Direct object property access - no CLDR ordering needed!
      if (forms[rule]) {
        return forms[rule];
      }
      
      // Fallback priority: other > one > first available
      return forms.other || forms.one || Object.values(forms)[0] || '';
    }
    },
    "buttons": {
      "catalog": "Browse catalog"
    }
  },
  "ru-RU": {
    "native": "Русский",
    "hello": "Привет",
    "bye": "Пока",
    "example": {
      "hello": "Привет"
    },
    "items": {
      "count": {
        "0": {
          "one": "предмет",
          "other": "предметы"
        }
      }
    },
    "product": {
      "count": {
        "0": {
          "one": "товар",
          "other": "товары"
        }
      }
    },
    "test": {
      "cars": {
        "0": {
          "one": "автомобиль",
          "other": "автомобили"
        }
      }
    },
    "buttons": {
      "catalog": "Перейти в каталог"
    }
  }
};

export const languages = ["en-US","en","ru-RU"];
