// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "test": {
      "title": "Title"
    }
  },
  "ru-RU": {
    "native": "Русский",
    "locale": "ru-RU",
    "test": {
      "title": "Заголовок"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["en-US","ru-RU"];
