// Auto-generated by i18n CLI - do not edit manually

export const dictionaries = {
  "en-US": {
    "test": {
      "title": "Title"
    }
  },
  "ru-RU": {
    "test": {
      "title": "Заголовок"
    }
  }
};

export const locales = ["en-US","ru-RU"];
