/**
 * Build system for i18n dictionaries with JavaScript function support
 * Converts YAML files to browser-compatible JavaScript module
 *
 * @author claude-4-sonnet
 */

import { writeFileSync, readdirSync } from 'fs'
import { resolve } from 'path'
import { load } from './load'

/**
 * Generate TypeScript type definitions for the dictionary structure
 */
function generateTypeDefinitions(dictionaries: Record<string, any>): string {
  const languages = Object.keys(dictionaries).map(lang => `'${lang}'`).join(' | ')

  // Use the English dictionary as the structure reference since it's the source
  const firstDict = dictionaries.en || Object.values(dictionaries)[0]
  const dictionaryType = generateDictionaryType(firstDict, 2)

  return `/**
 * Auto-generated TypeScript definitions for i18n dictionaries
 * Generated at: ${new Date().toISOString()}
 * 
 * @author claude-4-sonnet
 */

import type { Snippet } from 'svelte'

export type Language = ${languages}

export type Dictionary = ${dictionaryType}
`
}

/**
 * Recursively generate TypeScript type definition for dictionary structure
 */
function generateDictionaryType(obj: any, indent = 0): string {
  const spaces = '  '.repeat(indent)
  const nextSpaces = '  '.repeat(indent + 1)

  // Handle empty or null objects
  if (!obj || typeof obj !== 'object') {
    return '{}'
  }

  const entries = Object.entries(obj).map(([key, value]) => {
    let type: string

    if (typeof value === 'function') {
      const paramCount = value.length

      if (paramCount === 0)
        type = 'Snippet'
      else {
        const params = Array(paramCount).fill('any').join(', ')

        type = `Snippet<[${params}]>`
      }
    } else if (typeof value === 'string')
      type = 'Snippet'

    else if (typeof value === 'object' && value !== null)
      type = generateDictionaryType(value, indent + 1)
    else
      type = 'unknown'

    return `${nextSpaces}${key}: ${type}`
  })

  return `{\n${entries.join('\n')}\n${spaces}}`
}

/**
 * Serialize object with functions to JavaScript code
 */
function serializeWithFunctions(obj: any, indent = 0): string {
  const spaces = '  '.repeat(indent)
  const nextSpaces = '  '.repeat(indent + 1)

  if (typeof obj === 'function')
    return obj.toString()

  if (Array.isArray(obj)) {
    const items = obj.map(item => nextSpaces + serializeWithFunctions(item, indent + 1))

    return `[\n${items.join(',\n')}\n${spaces}]`
  }

  if (obj !== null && typeof obj === 'object') {
    const entries = Object.entries(obj).map(([key, value]) => {
      const serializedValue = serializeWithFunctions(value, indent + 1)

      return `${nextSpaces}"${key}": ${serializedValue}`
    })

    return `{\n${entries.join(',\n')}\n${spaces}}`
  }

  return JSON.stringify(obj)
}

/**
 * Build all YAML dictionaries into a single JavaScript file
 * that can be imported in the browser
 */
export function build(i18nPath = './src/lib/intl/'): void {
  console.log('🔨 Building dictionaries...')

  const i18nDir = resolve(process.cwd(), i18nPath)

  // Get all YAML language files
  const languageFiles = readdirSync(i18nDir)
    .filter(file => file.match(/^[a-z]{2}\.yaml$/))

  if (languageFiles.length === 0) {
    console.log('❌ No YAML language files found')

    return
  }

  const dictionaries: Record<string, any> = {}

  // Load each language and process functions
  for (const file of languageFiles) {
    const lang = file.replace('.yaml', '')
    const filePath = resolve(i18nDir, file)

    try {
      const dictionary = load(filePath)

      dictionaries[lang] = dictionary
      console.log(`✓ Processed ${lang}.yaml`)
    } catch (error) {
      console.error(`❌ Failed to process ${lang}.yaml:`, error)
      throw error
    }
  }

  // Generate JavaScript file content with proper function serialization
  const jsContent = `// Auto-generated by i18n CLI - do not edit manually
// Generated at: ${new Date().toISOString()}

export const dictionaries = ${serializeWithFunctions(dictionaries)};

export const languages = ${JSON.stringify(Object.keys(dictionaries))};
`

  // Generate TypeScript definitions
  const tsContent = generateTypeDefinitions(dictionaries)

  // Write both files in the same directory as i18n files
  const jsOutputPath = resolve(i18nDir, 'built.js')
  const tsOutputPath = resolve(i18nDir, 'types.ts')

  writeFileSync(jsOutputPath, jsContent)
  writeFileSync(tsOutputPath, tsContent)

  console.log(`✅ Built dictionaries for ${languageFiles.length} languages → built.js & types.ts`)
  console.log(`   Languages: ${Object.keys(dictionaries).join(', ')}`)
}
