// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": null,
  "ru-RU": null
};

export const locales = ["en-US","ru-RU"];
