// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<string, import("./types").Dictionary>} */
export const dictionaries = {
  "en-US": {
    "test": "Partition is here"
  },
  "ru-RU": {
    "native": "Русский",
    "locale": "ru-RU",
    "test": "Раздел здесь"
  }
};

/** @type {string[]} */
export const locales = ["en-US","ru-RU"];
