Feature: Build

  Scenario: Build
    When I run `npx intl hola -p ./test`
    And I run `npx intl add hello "Hello" -p ./test`
    And I run `npx intl create ru-RU -p ./test`
    Then the directory `test` contains:
      """
      - en-US.yaml
      - ru-RU.yaml
      - built.js
      - types.ts
      - index.ts
      """
    And the file `test/en-US.yaml` contains:
      """
      hello: Hello
      """
    And the file `test/ru-RU.yaml` contains:
      """
      hello: Здравствуйте
      """
    When I modify `test/en-US.yaml` to update `hello` to `Hello2`
    Then the file `test/en-US.yaml` contains:
      """
      hello: Hello2
      """
    When I run `npx intl build -p ./test`
    And the directory `test` contains:
      """
      - en-US.yaml
      - ru-RU.yaml
      - built.js
      - types.ts
      - index.ts
      """
    And the file `test/built.js` contains:
      """
      // Auto-generated by i18n CLI - do not edit manually

      /** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
      export const dictionaries = {
        "en-US": {
          "native": "English",
          "locale": "en-US",
          "hello": "Hello2"
        },
        "ru-RU": {
          "native": "Русский",
          "locale": "ru-RU",
          "hello": "Здравствуйте"
        }
      };

      /** @type {import('./types').Locale[]} */
      export const locales = ["en-US","ru-RU"];
      """
    When I run `npx intl mount foo ./test-foo/foo -p ./test`
    And I run `npx intl add foo/hello "Hello" -p ./test`
    Then the directory `test-foo/foo` contains:
      """
      - en-US.yaml
      - ru-RU.yaml
      - built.js
      - types.ts
      - index.ts
      """
    And the file `test-foo/foo/en-US.yaml` contains:
      """
      hello: Hello
      """
    And the file `test-foo/foo/ru-RU.yaml` contains:
      """
      hello: Здравствуйте
      """
    And the file `test-foo/foo/built.js` contains:
      """
      // Auto-generated by i18n CLI - do not edit manually

      /** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
      export const dictionaries = {
        "en-US": {
          "hello": "Hello"
        },
        "ru-RU": {
          "hello": "Здравствуйте"
        }
      };

      /** @type {import('./types').Locale[]} */
      export const locales = ["en-US","ru-RU"];
      """
    When I modify `test-foo/foo/en-US.yaml` to update `hello` to `Hello2`
    Then the file `test-foo/foo/en-US.yaml` contains:
      """
      hello: Hello2
      """
    When I run `npx intl build -p ./test`
    And the file `test-foo/foo/built.js` contains:
      """
      // Auto-generated by i18n CLI - do not edit manually

      /** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
      export const dictionaries = {
        "en-US": {
          "hello": "Hello2"
        },
        "ru-RU": {
          "hello": "Здравствуйте"
        }
      };

      /** @type {import('./types').Locale[]} */
      export const locales = ["en-US","ru-RU"];
      """

  Scenario: Build with JS function single argument types
    When I run `npx intl hola -p ./test-js`
    And I run `npx intl create ru-RU -p ./test-js`
    And I modify `test-js/en-US.yaml` to add:
      """
      formatSingle: |
        !js
        (value) => `Formatted: ${value}`
      """
    And I modify `test-js/ru-RU.yaml` to add:
      """
      formatSingle: |
        !js
        (value) => `Отформатировано: ${value}`
      """
    When I run `npx intl build -p ./test-js`
    Then the file `test-js/types.ts` contains:
      """
      formatSingle: (value: any) => string
      """
